services:
  postgres:
    image: postgres:16-alpine
    container_name: multiclinica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: multiclinica
      POSTGRES_USER: multiclinica
      POSTGRES_PASSWORD: multiclinica
    ports:
      - "5432:5432"
    volumes:
      - multiclinica-postgres:/var/lib/postgresql/data

volumes:
  multiclinica-postgres:
